### ISSUE TITLE
Next Available Network

### ISSUE THREAD

**Issue by donwlewis** [infobloxopen/infoblox-go-client#104]
We are looking to get some functionality where we can get the next available network from this client.  Ideally that would then bleed into Terraform functionality that we would like to leverage.

**Comment by donwlewis** [comment]
I think I found the function in question.  AllocateNetwork function seems to do the trick.  I will check to see how we can get that used in Terraform provider.

**Comment by somashekhar** [comment]
The support for getting Next Available Network has been added in our official repo {https://github.com/infobloxopen/terraform-provider-infoblox} and you can clone to use it.

**Comment by somashekhar** [comment]
Closing with above discussion.
