### ISSUE TITLE
Possibility to UPDATE a CNAME entry

### ISSUE THREAD

**Issue by deromemont** [infobloxopen/infoblox-go-client#110]
related to https://github.com/terraform-providers/terraform-provider-infoblox/issues/36

Possibility to update a CNAME in the GO Library

It seems possible with the API

`curl -k -u admin:infoblox -H 'content-type: application/json' -X PUT "https://gridmaster/wapi/v2.11/record:cname/ZG5zLmJpbmRfY25hbWUkLl9kZWZhdWx0LmNvbS5pbmZvLmRlbW8uY2
5hbWV0ZXN0:cnametest.demo.info.com/default?_return_fields%2B=name&_return_as_object=1" -d
'{"name":"cname.demo.info.com"}'`

**Comment by mmckane** [comment]
I would like to see this implemented as well.

**Comment by somashekhar** [comment]
An update functionality has been added to CNAME Record. Please do use the same and provide feedback. We would work on to support it under Terraform.

**Comment by somashekhar** [comment]
Now the feature is available at `master` branch. Will be available as part of `v2.0.0`
