### ISSUE TITLE
Feature Request: Ability to add comments

### ISSUE THREAD

**Issue by bmayfi3ld** [infobloxopen/infoblox-go-client#116]
As the title says, I would like to add a comment to these records I'm creating. This may not work well with some of the "New" functions since it would break people's code, but it looks like it could be added to all the objects with the appropriate json tags.

**Comment by somashekhar** [comment]
Hi @bmayfi3ld the enhancement to support comments for multiple records has been done and we are working on supporting new records with comment field. The Changes are in develop branch [https://github.com/infobloxopen/infoblox-go-client/tree/develop](url) . Please do use the same and provide the feedback.

**Comment by somashekhar** [comment]
Now the feature is available at `master` branch. Will be available as part of `v2.0.0`

**Comment by bmayfi3ld** [comment]
@somashekhar Thanks for getting to it, apologies I was not able to test it.

**Comment by somashekhar** [comment]
> @somashekhar Thanks for getting to it, apologies I was not able to test it.

No problem😊. Was able to test it and merge.
