### ISSUE TITLE
Feature: Add ability to set extensible attributes when creating a network

### ISSUE THREAD

**Issue by GNewbury1** [infobloxopen/infoblox-go-client#119]
Add the ability to create extensible attributes when creating a network. This will be useful in getting details where specific networks might have specific infrastructure items attached to them - for example, getting a DNS server for a particular network.

**Comment by somashekhar** [comment]
Hi @GNewbury1 the enhancement has been done and changes are in develop branch [https://github.com/infobloxopen/infoblox-go-client/tree/develop](url) . Please do use the same and provide the feedback.

**Comment by somashekhar** [comment]
Now the feature is available at `master` branch. Will be available as part of `v2.0.0`
