### ISSUE TITLE
ObjectManager does not implement IBObjectManager

### ISSUE THREAD

**Issue by survivorbat** [infobloxopen/infoblox-go-client#121]
Hey guys, I'm trying to create a REST API around InfoBlox and I'm attempting to use dependency injection using interfaces and structs so I can mock the IBObjectManager in my tests.

Now when I try to create an ObjectManager using:

```go
func GetInfoBloxObjectManager() *ibclient.IBObjectManager {
  // [...]
  return &ibclient.NewObjectManager(conn, "client", "")
}
```

My IDE shows me the error: 

`Type does not implement 'ibclient.IBObjectManager' need method: GetCNAMERecordByRef(ref string) (*RecordA, error) have method: GetCNAMERecordByRef(ref string) (*RecordCNAME, error)`

Is IBObjectManager not supposed to be the interface of the ObjectManager? Or am I doing something wrong here?

**Comment by marcowork** [comment]
I had the same error +1!

**Comment by survivorbat** [comment]
Edit:

Found another discrepancy:
`need method: GetZoneAuthByRef(ref string) (*ZoneAuth, error) have method: GetZoneAuthByRef(ref string) (ZoneAuth, error)`

**Comment by marcowork** [comment]
@survivorbat, what version of infoblox are you using?

**Comment by survivorbat** [comment]
Created #132

**Comment by survivorbat** [comment]
This issue is resolved in the develop branch, I'll await release
