### ISSUE TITLE
Feature request: add host aliases get/create/update

### ISSUE THREAD

**Issue by hrez** [infobloxopen/infoblox-go-client#126]
Please add host aliases.

Thanks.

**Comment by anagha-infoblox** [comment]
Sure. We will be adding it along with our upcoming feature.

**Comment by somashekhar** [comment]
Hi @hrez  the enhancement has been done and changes are in develop branch [https://github.com/infobloxopen/infoblox-go-client/tree/develop](url) . Please do use the same and provide the feedback.

**Comment by somashekhar** [comment]
Now the feature is available at `master` branch. Will be available as part of `v2.0.0`.
