### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by arvin-a** [infobloxopen/infoblox-go-client#129]
Please create a new release so the latest code can be referenced by External DNS Infoblox plugin build.

**Comment by somashekhar** [comment]
Hi Arvin,
We have couple more PRs to be reviewed. Expect a release to be done in a day or so.

**Comment by somashekhar** [comment]
Arvin we have published a new release [https://github.com/infobloxopen/infoblox-go-client/releases/tag/v1.1.1](url)

**Comment by arvin-a** [comment]
Thanks. I see the new release
