### ISSUE TITLE
Recent update removed "Ipv4Addr" field from RecordHost (now HostRecord)

### ISSUE THREAD

**Issue by eest** [infobloxopen/infoblox-go-client#59]
Hello,

I tried updating to 0.6.0 and it broke my code. The initial problem was that Host record related structs had been renamed from "RecordHost[...]" to "HostRecord[...]". While I guess that "HostRecord" reads a bit more naturally it's a bit strange since all other record types are still called "RecordA", "RecordCNAME" etc.

I can live with that change, but I also noticed the now renamed HostRecord struct no longer contains the field "Ipv4Addr". I have been using that to search for hosts by IP address like so:
```
var hostResult []ibclient.RecordHost

recordHostObj := ibclient.NewRecordHost(ibclient.RecordHost{
    Ipv4Addr: ip,
})

err := conn.GetObject(recordHostObj, "", &hostResult)
```

This of course no longer works. Was this removed on purpose and I am supposed to fill in an Ipv4Addrs slice instead or should it be added back?

Pinging @saiprasannasastry and @jkraj since you were involved in changing the code.

**Comment by jkraj** [comment]
@eest Yes it is modified intentionally.  Present structure represents actual wapi object representation. So you should use Ipv4Addrs slice.

**Comment by chinmayb** [comment]
Looks like we need to keep "Ipv4addr" field along with "Ipv4addrs"  as well @jkraj .  If you see the doc "wapidoc/objects/record.host.html#ipv4addr" Ipv4addr of string type is searchable, while ipv4addrs is not.

**Comment by eest** [comment]
@chinmayb: I applied the diff to my 0.6.0 branch and it made my search work, thanks!

**Comment by eest** [comment]
I noticed #69 has been merged, it would be great if you could create a new tag when this is also solved so i have a version that supports both host searching by ip address and the FixedAddress name addition from 0.5.0 :).

**Comment by chinmayb** [comment]
@eest you can use 0.7.0 version.

**Comment by eest** [comment]
@chinmayb: I can not, because 0.7.0 does not include the fix for FixedAddress added in #69.

**Comment by chinmayb** [comment]
I had updated the tag by force pushing. It didnt seem to work. I created a new release v0.7.1. Please use that

**Comment by eest** [comment]
@chinmayb the 0.7.1 tag seems to work as expected, thanks!
