### ISSUE TITLE
FixedAddress: "Name" field is not filled in when searching

### ISSUE THREAD

**Issue by eest** [infobloxopen/infoblox-go-client#62]
Hello,

Starting with version 0.5.0 the FixedAddress struct contains a "Name" field which I had use for. I noticed however that the Name field will always be empty when searching. This is because at least in my WAPI version the wapidoc states that only "ipv4addr" and  "network_view" is included in the basic object and `NewFixedAddress()` does not include "name" when filling in the `returnFields` slice:
```
func NewFixedAddress(fixedAddr FixedAddress) *FixedAddress {
        res := fixedAddr
        res.objectType = "fixedaddress"
        res.returnFields = []string{"extattrs", "ipv4addr", "mac", "network", "network_view"}

        return &res
}
```

Since `returnFields` is unexported I can not add "name" from my own code. I noticed there seemed to exist some basic idea of having a function to modify this slice because of a commented out `SetReturnFields()` function:
```
type IBObject interface {
        ObjectType() string
        ReturnFields() []string
        EaSearch() EASearch
        //SetReturnFields([]string)
}
```

... but I see no further traces of such code.

**Comment by eest** [comment]
@jkraj: I guess you should have more input on this since you added the "Name" field in the struct.

**Comment by jkraj** [comment]
@eest Since **name** is not searchable I didn't add that into _returnFields_ slice. If I include it will solve your issue.

**Comment by chinmayb** [comment]
https://github.com/infobloxopen/infoblox-go-client/pull/69
