### ISSUE TITLE
How to get a Ref?

### ISSUE THREAD

**Issue by luisdavim** [infobloxopen/infoblox-go-client#76]
Hi,

How do I get object refs? For example, I want to delete a CNAME and `DeleteCNAMERecord` takes one parameter `ref string`...

Thanks

**Comment by saiprasannasastry** [comment]
object manager does not have a function to get the record by the values, buit if its a new value your are creating, you can always store it in a variable and pass variable.Ref to delete.
But if the record has already been deleted you can do get records curl call and pass that ref as a string
