### ISSUE TITLE
Unknown extensible attribute: Cloud API Owned

### ISSUE THREAD

**Issue by dsbrng25b** [infobloxopen/infoblox-go-client#79]
I would like to use the AllocateIP function on a on-prem infoblox environment with WAPI Version 2.3.1 but i get the error: `Unknown extensible attribute: Cloud API Owned`.
It would be nice if the object_manager functions could be used on on-prem instances as well.

**Comment by saiprasannasastry** [comment]
Hi, can you please address the comments on the PR

**Comment by dhawal55** [comment]
Why are these attributes hard-coded in code? https://github.com/infobloxopen/infoblox-go-client/blob/6e85b72befc9d1ae6bb5de12aa201791339209f1/object_manager.go#L63-L69

The go-client should allow users to set the required attributes instead of the ones in the code above

**Comment by somashekhar** [comment]
These are the default EAs we get once CNA license is being installed and used. So we have made sure to get them in this method, so that subsequent methods can use them.

**Comment by dhawal55** [comment]
Thank you @somashekhar. Is the CNA license required in order to use this library?

**Comment by somashekhar** [comment]
If you don't have CNA then you should add these EAs manually and get library working.

**Comment by dhawal55** [comment]
We have static license with NIOS, DNS, DHCP, Discovery, Grid features but
not CNA. Looks like CNA is included in the AWS marketplace version. It
doesn't make sense to hard-code these EAs in the client library if they
don't come pre-installed with all licenses. I think a better solution is
would to provide an option to not set these EAs in the client library. I
can create a PR if you agree with it.

**Comment by somashekhar** [comment]
Agree. That would be a better solution. Do make sure nothing breaks and also add new UTs. 
@AvRajath can you once confirm this proposal does not break anything in our existing Terraform plugin.

**Comment by dhawal55** [comment]
Also, it replaces the EA object passed to the function call instead of appending to it. I will submit the MR
