### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by nulldowntime** [infobloxopen/infoblox-go-client#82]
Hi, is this project active? Is there any work happening to e.g. add update support for DNS records?

This is not great:
https://github.com/infobloxopen/terraform-provider-infoblox/blob/ffd58a18c23af88c1265df8cb284acfea4664b16/infoblox/resourceARecord.go#L121

**Comment by saiprasannasastry** [comment]
@nulldowntime  the use case for terraform provider was to provide VM's to IP for the VM's created , in that scenario we dont want to update the DNS name once VM has been created, hence the update was not implemented

**Comment by nulldowntime** [comment]
OK, I understand you didn't need it specifically for Terraform, but what about general functionality of the go client? Surely making it "fully-featured" would make sense?

It would be great to know if further development, especially around DNS records updates, is planned, some timelines, etc. 

Thanks in advance!

**Comment by saiprasannasastry** [comment]
cant provide strict timeline , but will make sure the project is active and also try to write the update calls for existing DNS functionality

**Comment by saiprasannasastry** [comment]
FYI Working on the enhancments

**Comment by somashekhar** [comment]
The newly added features are available at `master` branch. Will be available as part of `v2.0.0`.

Feel free to raise a request if you have any other specific requirements.
