### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by nahun** [infobloxopen/infoblox-go-client#86]
Enhancement request to support IPv6 in all applicable functions and objects and add AAAA support.

**Comment by somashekhar** [comment]
Hi @nahun,
IPv6 support for DHCP objects has been done and we are working on supporting DNS objects. 
The changes are in develop branch [https://github.com/infobloxopen/infoblox-go-client/tree/develop](url) . Please do use the same and provide the feedback.

**Comment by somashekhar** [comment]
We have added support for DNS objects as well.

Now the feature is available at `master` branch. Will be available as part of `v2.0.0`
