### ISSUE TITLE
DeleteNetworkContainer

### ISSUE THREAD

**Issue by pearcec** [infobloxopen/infoblox-go-client#95]
The go client has a CreateNetworkContainer and GetNetworkContainer but not DeleteNetworkContainer.  There is a request in the terraform-provider-infoblox to include Network containers as a resource.  We will want Delete to do testing and not have a dangling resource and people expect it.

infobloxopen/terraform-provider-infoblox/issues/27

**Comment by somashekhar** [comment]
Hi @pearcec  the enhancement has been done and changes are in develop branch [https://github.com/infobloxopen/infoblox-go-client/tree/develop](url) . Please do use the same and provide the feedback.

The respective code changes at Terraform are also done. Clone the latest Terraform code from `develop` branch to get the features.

**Comment by pearcec** [comment]
Thanks, but I no longer work for the company that uses this.

**Comment by somashekhar** [comment]
Hope we can close the issue then.
